kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: wordpress-mariadb-pvc
  annotations:
    openshift.io/display-name:  Deployment mariadb persistent volume claim for the WordPress deploy.
    description: Deployment mariadb persistent volume claim for the WordPress deploy.
    tags: mariadb,wordpress,pvc

parameters:
  - name: APP_NAME
    displayName: "App Name"
    description: "The name of the application (grouped)."
    required: true
    value: "wordpress"
  - name: ROLE_NAME
    displayName: "Component Name"
    description: "The name of the application role."
    required: true
    value: "mariadb"
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "c0cce6"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "dev"
  - name: VOLUME_SIZE
    displayName: "Volume size"
    description: "The Volume size ie 1Gi"
    required: true
    value: "500M"
  - name: SITE_NAME
    displayName: "Site name"
    description: "The name for the site (a-zA-Z_)"
    required: true
    value: "global"

objects:
  # PVC for the runtime image.
  - kind: "PersistentVolumeClaim"
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}--${SITE_NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: "${VOLUME_SIZE}"
      storageClassName: netapp-block-standard
      volumeMode: Filesystem
