name: Build Nginx Image.
on:
  workflow_run:
    workflows: ["Check for new WordPress Docker image"]
    types: 
      - completed
  push:
    branches:
      - main
    paths:
      - "openshift/templates/images/nginx/**/*"
  workflow_dispatch:
defaults:
  run:
    working-directory: ./
jobs:
  oc:
    uses: bcgov/wordpress/.github/workflows/oc-build-image.yaml@main
    with:
      image: wordpress-nginx-run
    secrets:
      openshift_server_url: ${{ secrets.OpenShiftServerURL }}
      openshift_token: ${{ secrets.OpenShiftToken }}
      openshift_licenseplate: ${{ secrets.OPENSHIFT_LICENSEPLATE }}