name: Build Sidecar Utility Image.
on:
  push:
    branches:
      - main
    paths:
      - "openshift/templates/images/sidecar/**/*"
  workflow_dispatch:
defaults:
  run:
    working-directory: ./
jobs:
  deploy:
    if: github.repository_owner == 'bcgov'
    runs-on: ubuntu-latest
    steps:
      - name: Image Build for Sidecar utility Image
        uses: redhat-developer/openshift-actions@v1.1
        with:
          version: "latest"
          openshift_server_url: ${{ secrets.OpenShiftServerURL }}
          parameters: '{"apitoken": "${{ secrets.OpenShiftToken }}", "acceptUntrustedCerts": "true"}'
          cmd: |
            oc project c0cce6-tools
            oc start-build wordpress-sidecar-run --follow