name: Build WordPress Image.
on:
  workflow_run:
    workflows: ["Check for new WordPress Docker image"]
    types: 
      - completed
  push:
    branches:
      - main
    paths:
      - "openshift/templates/images/wordpress/**/*"
  workflow_dispatch:
defaults:
  run:
    working-directory: ./
jobs:
  oc:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    uses: bcgov/wordpress-deploy-digimod/.github/workflows/oc-build-image.yaml@main
    with:
      image: wordpress-wordpress-run
    secrets:
      openshift_server_url: ${{ secrets.OpenShiftServerURL }}
      openshift_token: ${{ secrets.OpenShiftToken }}
      openshift_licenseplate: ${{ secrets.OPENSHIFT_LICENSEPLATE }}
