# digital-latest/patch.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wordpress-nginx
  annotations:
     haproxy.router.openshift.io/ip_whitelist: >-
      142.32.0.0/16
     haproxy.router.openshift.io/ip_whitelist_comment: >-
      #CIDR 142.32.0.0/16 only allow BC Gov internal ips
spec:
  host: digital-latest.apps.silver.devops.gov.bc.ca
  to:
    kind: Service
    name: digital-latest-wordpress-nginx
    weight: 100 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: webserver
    app.kubernetes.io/part-of: wordpress
    app.openshift.io/runtime: nginx
  name: wordpress
  namespace: default
spec:
  template:
    spec:
      volumes:
      - name: php-fpm-secrets-volume
        secret:
          defaultMode: 420
          secretName: digital-latest-wordpress-secrets
      - name: mariadb-secrets-volume
        secret:
          defaultMode: 420
          items:
          - key: MYSQL_PASSWORD
            path: MYSQL_PASSWORD
          secretName: digital-latest-wordpress-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: coreDB
    app.kubernetes.io/part-of: wordpress
  name: wordpress-mariadb
  namespace: default
spec:
  template:
    spec:
      volumes:
      - name: db-secrets-volume
        secret:
          defaultMode: 420
          items:
          - key: MYSQL_PASSWORD
            path: mysql_password
          - key: MYSQL_ROOT_PASSWORD
            path: mysql_root_password
          secretName: digital-latest-wordpress-secrets


